all: count_words 2_1a 2_1b 2_1d 2_2a 2_2b 2_2c 3

count_words: count_words.c
	gcc -m32 -g -Wall -c -o count_words.o count_words.c 
2_1a:
	gcc -m32 -g -Wall -c -o sl2_adresses.o sl2_adresses.c 

2_1b:
	gcc -m32 -g -Wall -c -o sl2_1b.o sl2_1b.c 

2_1d:
	gcc -m32 -g -Wall -c -o sl2_1d.o sl2_1d.c 
2_2a:
	gcc -m32 -g -Wall -c -o sl2_2a.o sl2_2a.c 
2_2b: 
	gcc -m32 -g -Wall -c -o sl2_2b.o sl2_2b.c 
2_2c:
	gcc -m32 -g -Wall -c -o sl2_2c.o sl2_2c.c 
3: 
	gcc -m32 -g -Wall -c -o 3.0 3.c
clean: 
	rm -f *.o 

 
